// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQPTs4wCllISy5wvy5vaesEpgRFSMB-Y',
    appId: '1:549281312315:web:c1cc25326c3946de5f361e',
    messagingSenderId: '549281312315',
    projectId: 'construction-helper-f7c00',
    authDomain: 'construction-helper-f7c00.firebaseapp.com',
    storageBucket: 'construction-helper-f7c00.firebasestorage.app',
    measurementId: 'G-SWYGD6K13R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzJDtfxNK02ateqTRf2b-ym0jywvvYQkY',
    appId: '1:549281312315:android:ddd96ee9bbf94d3c5f361e',
    messagingSenderId: '549281312315',
    projectId: 'construction-helper-f7c00',
    storageBucket: 'construction-helper-f7c00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA43DEhe5bSP9GEvyE7zHLULICLdV2oPPE',
    appId: '1:549281312315:ios:895afd9304c13ad65f361e',
    messagingSenderId: '549281312315',
    projectId: 'construction-helper-f7c00',
    storageBucket: 'construction-helper-f7c00.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA43DEhe5bSP9GEvyE7zHLULICLdV2oPPE',
    appId: '1:549281312315:ios:895afd9304c13ad65f361e',
    messagingSenderId: '549281312315',
    projectId: 'construction-helper-f7c00',
    storageBucket: 'construction-helper-f7c00.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYQPTs4wCllISy5wvy5vaesEpgRFSMB-Y',
    appId: '1:549281312315:web:0ad829ad5969086e5f361e',
    messagingSenderId: '549281312315',
    projectId: 'construction-helper-f7c00',
    authDomain: 'construction-helper-f7c00.firebaseapp.com',
    storageBucket: 'construction-helper-f7c00.firebasestorage.app',
    measurementId: 'G-Y5PH73JLDP',
  );
}
